version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-jupyter-container
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks

